### ISSUE TITLE
Scanning works, but gscan2pdf exports empty page/s when saving, GIMP, or printing. Selecting one of the thumbnails does not change the full size image in the right window

### ISSUE THREAD

**Issue by Wikinaut** [marschap/gscan2pdf#1]
RE: gscan2pdf 1.3.0 from the sources under OpenSuse Tumbleweed
### Problem: scanning works, but empty blank pages when saving or printing

I had many problems to get a version running under OpenSuse, but now I could install something from https://software.opensuse.org. I could now also compile the latest version from SF.

gscan2pdf --version reports gscan2pdf 1.3.0

It does scan multiple pages from my older BROTHER MFC-7820N and I do see the multiple thumbnails and the last page is shown fully in the viewing panel.
### BUT:

when trying to select another page (e.g. the first page) from the thumbnails in the left column -> nothing happens. Still the last page is shown in the right window.
### Bug:

When trying to save or to print all pages, or a single page: empty page/s !
From the log file (excerpt)

WARN - GLib-GObject-WARNING **: The property GtkDialog:has-separator is deprecated and should
n't be used anymore. It will be removed in a future version. at ./gscan2pdf line 4742.

(several lines like the following:)
WARN - unhandled exception in callback:
Image file '/tmp/gscan2pdf-BYmN/qllMRPI4B7.pnm' contains no data at ./gscan2pdf line 47
21.
**\* ignoring at ./gscan2pdf line 4742.

Perhaps I overlooked a simple stupid thing?
Pls. assist. Let me know if you need further data.

**Comment by marschap** [comment]
this repository is only a clone of the uspream repository at git://git.code.sf.net/p/gscan2pdf/code
to publish my fixes.
I will ignore any bug report or pull request to this repo.
Please get in contact with upstream directly at http://gscan2pdf.sourceforge.net/
